// Generated by Selenium IDE
const { Builder, By } = require('selenium-webdriver');

async function getStats() {
  let driver = await new Builder().forBrowser('chrome').build();
  await driver.get("https://www.coronavirus.in.gov/map-test/test.htm");
  const totalPositiveCases = await driver.findElement(By.id("total_pt")).getText();
  const totalDeaths = await driver.findElement(By.id("deaths")).getText();
  driver.close();
  return {
    'IN': {
      totalPositiveCases,
      totalDeaths
    }
  };
}

module.exports.getStats = getStats; 